fixes issue with build flag

diff --git a/algo_owls b/algo_owls
--- a/algo_owls
+++ b/algo_owls
@@ -36,6 +36,7 @@ algo_owls_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   Compile target solution into the 'ALGO_TARGET' directory\n" "build"
   printf "  %s   Create solution file from a template (if desired)\n" "init "
+  printf "  %s   Run target solution\n" "run  "
   echo
 
   # :command.long_usage
@@ -111,7 +112,7 @@ algo_owls_build_usage() {
 
     # :flag.usage
     printf "  %s\n" "--ext, -e EXTENSION"
-    printf "    The file extension to use for the solution and template files\n"
+    printf "    The file extension to use for the solution file\n"
     echo
 
     # :command.usage_fixed_flags
@@ -215,6 +216,100 @@ algo_owls_init_usage() {
   fi
 }
 
+# :command.usage
+algo_owls_run_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "algo_owls run - Run target solution\n"
+    echo
+
+  else
+    printf "algo_owls run - Run target solution\n"
+    echo
+
+  fi
+
+  printf "Alias: r\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  algo_owls run SOLUTION [OPTIONS]\n"
+  printf "  algo_owls run --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--build, -b"
+    printf "    Execute the default build command prior to running the target solution\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--ext, -e EXTENSION"
+    printf "    The file extension to use for the solution\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--no_ext"
+    printf "    Ignore extensions when executing the target solution\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--run_cmd COMMAND"
+    printf "    The run command to use to execute the solution\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--run_flag FLAG"
+    printf "    The flag to use to specify 'ALGO_TARGET' as the target source directory\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--use_source"
+    printf "    Execute the target solution from within the 'ALGO_SOLUTIONS' directory\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "SOLUTION"
+    printf "    The name of the target solution from the 'ALGO_SOLUTIONS' directory\n"
+    echo
+
+    # :command.usage_environment_variables
+    printf "%s\n" "Environment Variables:"
+
+    # :environment_variable.usage
+    printf "  %s\n" "ALGO_RUN_CMD"
+    printf "    Set the default run command if no other run command is provided\n"
+    echo
+
+    # :environment_variable.usage
+    printf "  %s\n" "ALGO_RUN_FLAG"
+    printf "    Set the default source flag to use when executing solutions in the\n    'ALGO_TARGET' directory\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  algo_owls run fading_wind\n"
+    printf "  algo_owls run --build hunt_the_wumpus\n"
+    printf "  algo_owls run --no_ext champernowne_count\n"
+    printf "  algo_owls run --ext .py streets_ahead.py\n"
+    printf "  algo_owls build --no_ext --run_cmd java --run_flag --source restaurant_opening\n"
+    printf "  algo_owls run --use_source --ext .py color_tubes\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -289,12 +384,17 @@ algo_owls_build_command() {
       exit 1
   fi
 
+  BUILD_FLAG="${ALGO_BUILD_FLAG}"
+  if [[ ! -z ${args[--build_flag]} ]]; then
+      BUILD_FLAG="${args[--build_flag]}"
+  fi
+
   BUILD_CMD="${ALGO_BUILD_CMD}"
   if [[ ! -z ${args[--build_cmd]} ]]; then
       BUILD_CMD="${args[--build_cmd]}"
   fi
-  if [[ ! -z ${args[--build_flag]} ]]; then
-      BUILD_CMD="$BUILD_CMD ${args[--build_flag]} \$ALGO_TARGET"
+  if [[ ! -z $BUILD_FLAG ]]; then
+      BUILD_CMD="$BUILD_CMD $BUILD_FLAG $ALGO_TARGET"
   fi
   BUILD_CMD="$BUILD_CMD $TARGET_FILE"
 
@@ -336,6 +436,66 @@ algo_owls_init_command() {
 
   mkdir -p ${SOLUTION%/*}
   cp $TEMPLATE $SOLUTION
+
+}
+
+# :command.function
+algo_owls_run_command() {
+  # src/run_command.sh
+  echo "# this file is located in 'src/run_command.sh'"
+  echo "# code for 'algo_owls run' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
+
+  if [[ ! -z ${args[--build]} && ${args[--build]} == 1 ]]; then
+      if [[ ! -z ${args[--ext]} ]]; then
+          ./algo_owls build --ext ${args[--ext]} ${args[solution]}
+      else
+          ./algo_owls build ${args[solution]}
+      fi
+  fi
+
+  EXT="$ALGO_EXT"
+  if [[ ! -z ${args[--ext]} ]]; then
+      EXT="${args[--ext]}"
+  fi
+  if [[ ${EXT:0:1} != "." ]]; then
+      EXT=".$EXT"
+  fi
+
+  SOLUTION="${args[solution]}"
+  if [[ -z ${args[--no_ext]} || ${args[--no_ext]} == 0 ]]; then
+      SOLUTION="$SOLUTION$EXT"
+  fi
+
+  TARGET_DIR="$ALGO_TARGET"
+  if [[ ! -z ${args[--use_source]} && ${args[--use_source]} == 1 ]]; then
+      TARGET_DIR="$ALGO_SOLUTIONS"
+  fi
+
+  TARGET_FILE=$(find $TARGET_DIR -name $SOLUTION)
+
+  if [[ -z $TARGET_FILE ]]; then
+      echo "algo_owls: $SOLUTION: No such file or directory" 1>&2
+      echo "Try using: ./algo_owls run --build $SOLUTION"
+      exit 1
+  fi
+
+  RUN_FLAG="${ALGO_RUN_FLAG}"
+  if [[ ! -z ${args[--run_flag]} ]]; then
+      RUN_FLAG="${args[--run_flag]}"
+  fi
+
+  RUN_CMD="${ALGO_RUN_CMD}"
+  if [[ ! -z ${args[--run_cmd]} ]]; then
+      RUN_CMD="${args[--run_cmd]}"
+  fi
+  if [[ ! -z $RUN_FLAG ]]; then
+      RUN_CMD="$RUN_CMD $RUN_FLAG $TARGET_DIR"
+  fi
+  RUN_CMD="$RUN_CMD $TARGET_FILE"
+
+  eval $RUN_CMD
 
 }
 
@@ -385,6 +545,13 @@ parse_requirements() {
       action="init"
       shift
       algo_owls_init_parse_requirements "$@"
+      shift $#
+      ;;
+
+    run | r)
+      action="run"
+      shift
+      algo_owls_run_parse_requirements "$@"
       shift $#
       ;;
 
@@ -620,6 +787,130 @@ algo_owls_init_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+algo_owls_run_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        algo_owls_run_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="run"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --build | -b)
+
+        # :flag.case_no_arg
+        args['--build']=1
+        shift
+        ;;
+
+      # :flag.case
+      --ext | -e)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--ext']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--ext requires an argument: --ext, -e EXTENSION" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --no_ext)
+
+        # :flag.case_no_arg
+        args['--no_ext']=1
+        shift
+        ;;
+
+      # :flag.case
+      --run_cmd)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--run_cmd']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--run_cmd requires an argument: --run_cmd COMMAND" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --run_flag)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--run_flag']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--run_flag requires an argument: --run_flag FLAG" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --use_source)
+
+        # :flag.case_no_arg
+        args['--use_source']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['solution']+x} ]]; then
+
+          args['solution']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['solution']+x} ]]; then
+    printf "missing required argument: SOLUTION\nusage: algo_owls run SOLUTION [OPTIONS]\n" >&2
+    exit 1
+  fi
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -645,6 +936,7 @@ run() {
   case "$action" in
     "build") algo_owls_build_command ;;
     "init") algo_owls_init_command ;;
+    "run") algo_owls_run_command ;;
   esac
 }
 
